In [102]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, precision_score, recall_score, f1_score
from sklearn import metrics
import joblib


In [103]:
labels = []
features = []
file = open('fixed_values_ds.csv').read()
list = file.split('\n')
data = np.array(list)
data_new = [i.split(',') for i in data]
data_new = data_new[0:-1]
for i in data_new:
    labels.append(i[28])
data_new = np.array(data_new)
print(data_new)
features = data_new[:, :-1]
print(features)
features = features[:, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]]
print(features)
features = np.array(features).astype(np.float)


[['-1' '-1' '-1' ... '-1' '-1' '1']
 ['-1' '0' '-1' ... '-1' '1' '1']
 ['-1' '-1' '-1' ... '-1' '1' '1']
 ...
 ['-1' '-1' '-1' ... '-1' '-1' '-1']
 ['-1' '-1' '-1' ... '-1' '1' '-1']
 ['-1' '-1' '-1' ... '-1' '-1' '-1']]
[['-1' '-1' '-1' ... '1' '-1' '-1']
 ['-1' '0' '-1' ... '-1' '-1' '1']
 ['-1' '-1' '-1' ... '-1' '-1' '1']
 ...
 ['-1' '-1' '-1' ... '1' '-1' '-1']
 ['-1' '-1' '-1' ... '1' '-1' '1']
 ['-1' '-1' '-1' ... '1' '-1' '-1']]
[['-1' '-1' '-1' ... '1' '-1' '-1']
 ['-1' '0' '-1' ... '-1' '-1' '1']
 ['-1' '-1' '-1' ... '-1' '-1' '1']
 ...
 ['-1' '-1' '-1' ... '1' '-1' '-1']
 ['-1' '-1' '-1' ... '1' '-1' '1']
 ['-1' '-1' '-1' ... '1' '-1' '-1']]


<ipython-input-103-f04a789eb146>:16: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  features = np.array(features).astype(np.float)


# Train Model
HAS TO BE CHANGED TO ALL ENTRIES OF THE DATASET

In [104]:
features_train=features
labels_train=labels
features_test=features[11000:]
labels_test=labels[11000:]
print(features_train)
print('\n\n\n')
print(labels_train)

[[-1. -1. -1. ...  1. -1. -1.]
 [-1.  0. -1. ... -1. -1.  1.]
 [-1. -1. -1. ... -1. -1.  1.]
 ...
 [-1. -1. -1. ...  1. -1. -1.]
 [-1. -1. -1. ...  1. -1.  1.]
 [-1. -1. -1. ...  1. -1. -1.]]




['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1'

# Random Forest

In [105]:
print("\n\n ""Results Based on Random Forest Algorithm"" ")
clf4 = RandomForestClassifier(min_samples_split=7, verbose=True)
clf4.fit(features_train, labels_train)
importances = clf4.feature_importances_
std = np.std([tree.feature_importances_ for tree in clf4.estimators_],
             axis=0)
indices = np.argsort(importances)[::-1]
# Print the feature ranking
print("Feature ranking:")
for f in range(features_train.shape[1]):
    print("%d. Feature %d (%f)" % (f + 1, indices[f], importances[indices[f]]))




 Results Based on Random Forest Algorithm 
Feature ranking:
1. Feature 24 (0.276761)
2. Feature 11 (0.263284)
3. Feature 6 (0.073731)
4. Feature 26 (0.071184)
5. Feature 25 (0.050368)
6. Feature 1 (0.049233)
7. Feature 5 (0.041774)
8. Feature 14 (0.020321)
9. Feature 15 (0.016673)
10. Feature 13 (0.016103)
11. Feature 23 (0.015155)
12. Feature 2 (0.014734)
13. Feature 27 (0.014700)
14. Feature 8 (0.013365)
15. Feature 22 (0.013334)
16. Feature 9 (0.010295)
17. Feature 12 (0.009544)
18. Feature 17 (0.006890)
19. Feature 3 (0.004807)
20. Feature 7 (0.003622)
21. Feature 19 (0.002908)
22. Feature 21 (0.002815)
23. Feature 16 (0.002451)
24. Feature 20 (0.002423)
25. Feature 18 (0.001428)
26. Feature 4 (0.001027)
27. Feature 0 (0.000974)
28. Feature 10 (0.000098)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.5s finished


# Results


In [106]:
pred4=clf4.predict(features_test)
print(classification_report(labels_test, pred4))
print ('Accuracy:', accuracy_score(labels_test, pred4))
print ('Precision:', precision_score(labels_test, pred4, pos_label="1"))
print ('Recall:', recall_score(labels_test, pred4, pos_label="1"))
print ('F1 Score:', f1_score(labels_test, pred4, pos_label="1"))
print('')
print ('Confusion Matrix')
print (metrics.confusion_matrix(labels_test, pred4))


              precision    recall  f1-score   support

          -1       0.97      0.99      0.98      1047
           1       1.00      0.98      0.99      2045

    accuracy                           0.99      3092
   macro avg       0.98      0.99      0.99      3092
weighted avg       0.99      0.99      0.99      3092

Accuracy: 0.9867399741267788
Precision: 0.9965312190287413
Recall: 0.9833740831295843
F1 Score: 0.989908934285011

Confusion Matrix
[[1040    7]
 [  34 2011]]


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s finished


In [107]:
joblib.dump(clf4, 'new_model.pkl', compress=9)

['new_model.pkl']